#!/usr/bin/env node
/**
 * IndexNow ping — submit fresh URLs to Bing/Yandex/Seznam in one call.
 *
 * Reads INDEXNOW_KEY from env (a UUID generated by the operator).
 * The same UUID must be served from /{key}.txt (file in public/).
 * Bing/Yandex fetch that file to verify ownership before accepting URLs.
 *
 * Setup (one-time, by operator):
 *   1. Generate a UUID:  node -e "console.log(crypto.randomUUID())"
 *   2. Set INDEXNOW_KEY=<uuid> in studio root .env.local
 *   3. Create public/<uuid>.txt containing exactly the UUID, no newline
 *   4. Deploy. Verify https://practiq.dev/<uuid>.txt returns the UUID.
 *
 * Daily run (Vercel cron or post-deploy hook):
 *   node scripts/indexnow-ping.mjs
 *
 * Submits a curated list of high-priority URLs that change frequently
 * (home, pricing, blog index, vertical hubs). Per-blog-post or per-
 * resource pings should be added when those routes are updated.
 */

const INDEXNOW_KEY = process.env.INDEXNOW_KEY;
const HOST = process.env.INDEXNOW_HOST || "practiq.dev";
const ENDPOINT = "https://api.indexnow.org/indexnow";

if (!INDEXNOW_KEY) {
  console.warn(
    "[indexnow] INDEXNOW_KEY not set — skipping ping. " +
      "See scripts/indexnow-ping.mjs header for setup.",
  );
  process.exit(0);
}

// High-frequency surfaces. Keep this list short — IndexNow rate-limits
// per-host and abuse trips Bing's spam filter. Per-post pings should be
// triggered from the publish hook, not from this daily sweep.
const URLS = [
  `https://${HOST}/`,
  `https://${HOST}/pricing`,
  `https://${HOST}/blog`,
  `https://${HOST}/compare`,
  `https://${HOST}/for/accounting`,
  `https://${HOST}/for/law`,
  `https://${HOST}/for/consulting`,
  `https://${HOST}/for/hr`,
  `https://${HOST}/for/agency`,
  `https://${HOST}/founding-member`,
  `https://${HOST}/faq`,
  `https://${HOST}/resources`,
];

const body = {
  host: HOST,
  key: INDEXNOW_KEY,
  keyLocation: `https://${HOST}/${INDEXNOW_KEY}.txt`,
  urlList: URLS,
};

try {
  const res = await fetch(ENDPOINT, {
    method: "POST",
    headers: { "Content-Type": "application/json; charset=utf-8" },
    body: JSON.stringify(body),
  });

  // IndexNow returns 200 (accepted), 202 (accepted, processing), 422 (invalid
  // URL list), 403 (key file not reachable / mismatch). Anything else is
  // unexpected — log and exit non-zero so cron alerts surface it.
  if (res.status === 200 || res.status === 202) {
    console.log(
      `[indexnow] OK ${res.status} — submitted ${URLS.length} URL(s) for ${HOST}`,
    );
    process.exit(0);
  }

  const text = await res.text().catch(() => "(no body)");
  console.error(`[indexnow] FAIL ${res.status} — ${text}`);
  process.exit(res.status === 403 ? 2 : 1);
} catch (err) {
  console.error("[indexnow] network error:", err?.message || err);
  process.exit(1);
}
