import type { Client, ClientContext } from "@/types/domain";

/**
 * Builds a client-specific system prompt for Claude.
 * This prompt gives the AI full context about the current client,
 * enabling it to produce accurate, contextual responses.
 *
 * The prompt is structured so the stable header (role, tools,
 * preferences) precedes the volatile sections (recent contexts,
 * applied patterns) — this matters for Anthropic's prompt caching:
 * cached prefix means cache-read tokens land on the stable parts.
 */
export function buildSystemPrompt(
  client: Client,
  recentContexts: ClientContext[],
  /**
   * Optional Markdown block of "previously-applied patterns" for this
   * client. Generated by `loadActiveRulesForPrompt + renderRulesForPrompt`
   * in src/lib/pattern-learner.ts. Empty string = no patterns yet
   * (free/Solo plans, or first few approvals on a new client). Always
   * pass through — the chat route is the single call site that has
   * the prisma binding to load rules and we keep this function pure.
   */
  rulesPromptBlock: string = "",
): string {
  const contextSummary = recentContexts
    .map((c) => `- [${c.category}] ${c.title}: ${c.content.slice(0, 200)}`)
    .join("\n");

  return `You are an AI assistant for a Fractional ${client.userRole} working with ${client.name}.

Company: ${client.name}
Industry: ${client.industry}
Relationship: ${client.relationshipMonths} months

[Your Role]
1. Answer questions using this client's specific data and context.
2. Generate documents (reports, spreadsheets, presentations, emails) tailored to this client.
3. Maintain consistency with previous outputs and the client's preferences.
4. Never reference or leak data from other clients.

[Output Preferences]
- Report tone: ${client.preferences?.reportTone ?? "professional"}
- Preferred formats: ${client.preferences?.preferredFormats?.join(", ") ?? "docx, xlsx"}

[Tool Use]
When generating documents, use the generate_document tool.
When you need more context, use the search_knowledge_base tool.
When drafting emails, use the draft_email tool.

[Client Context — Recent Knowledge]
${contextSummary || "No prior context available yet."}
${rulesPromptBlock}`;
}
